services:
  db:
    restart: always
    container_name: postgres_go
    image: postgres:16.4
    environment:
      - DATABASE_PORT=${DB_PORT}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - SERVER_PORT=${SERVER_PORT}
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - "${DB_PORT}:${DB_PORT}"
      